### ISSUE TITLE
DHCP doesn't work in 16-bit DOS

### ISSUE THREAD

**Issue by mateuszviste** [gvanem/Watt-32#4] opened 2020-01-23 23:29 UTC
This happens when the current master branch is compiled under a 16-bit real mode DOS target (watcom build, large memory model). I did not test other targets.

After calling sock_init(), WATT-32 prints out the usual "Configuring through DHCP.." message, and stays there. It never succeeds, and never timeouts - I have to reboot my PC. If executed with a static IP configuration, then the stack works fine. If I link my application against the older WATT-32 2.2 rel 10, then DHCP works fine.

There are, I think, two distinct problems here:
1. DHCP is unable to obtain a lease (maybe related to DHCP itself, or maybe to something else - like packet-sending routines...)
2. WATT-32 fails to timeout gracefully (freezes the computer)

**Comment by gvanem** [comment] 2020-01-24 09:15
I just tried DHCP on Win32/Visual-C. I doesn't work there either and even a `ping -sd host` freezes pretty good 🤕  I look into it.

**Comment by mateuszviste** [comment] 2020-01-24 10:02
Another (semi-related) thing I was thinking about - currently the DHCP code is linked in to every single application that relies on Watt-32. pcdhcp.obj and pcbootp.obj are together 20K big, that is roughly 5% of the entire library. In a constrained environment (like real-mode DOS), 20K is a lot of memory, and the application uses it only once anyway, during startup.

Maybe would it be possible to split the DHCP+BOOTP code out of the main library code into a separate utility of some sort? I'd imagine that an application could for example fail with such message:
````
ERROR: no valid DHCP lease found
Please run WATTDHCP.EXE to regenerate a %TEMP%\W32DHCP.TMP lease
````
This way, Watt-based applications could be ~20K lighter, without any functionality loss.

Would that make sense? What do you think?

**Comment by gvanem** [comment] 2020-01-24 11:25
Could be an idea. But that would require 2 Watt-32 libraries. One built with `USE_DHCP` and one without. IMHO it would just create more confusion than there already is.

But regarding `dhcp_fsm()`; I see that the 1st `send_timeout` is not always expiring as it should 
to start the initial DHCP discover process. Some weird timer issue??

```
my_ip = dhcp
;
; From INIT, this should call DHCP_discover() after 1 sec. It does *sometimes*
;
dhcp.timeout = 1
dhcp.retries = 3
```

**Comment by gvanem** [comment] 2020-01-24 11:38
Some *progress*. With this change:
```diff
--- a/src/pcdhcp.c
+++ b/src/pcdhcp.c
@@ -1023,7 +1023,7 @@ 
     }
   }

-  if (chk_timeout(send_timeout))
+  if (send_timeout == (DWORD)-1 || chk_timeout(send_timeout))
   {
     send_timeout = 0UL;
     TRACE (("%s/SEND_TIMEOUT: ", state_name()));
@@ -1080,9 +1080,15 @@
   erase_config();           /* delete old configuration */
   DAEMON_ADD (dhcp_fsm);    /* add "background" daemon */

-  /* kick start DISCOVER message
+#if 0
+  /* kick start DISCOVER message after 100 msec.
    */
   send_timeout = set_timeout (100);
+#else
+  /* kick start DISCOVER message now please
+   */
+  send_timeout = (DWORD)-1;
+#endif

   if (DHCP_state != DHCP_state_RENEWING &&
       DHCP_state != DHCP_state_REBINDING)
```

I see the DHCP Discover is sent:
```
Transmitted: pctcp.c (1570), time 00:00:00.073
ETH:   destin FF:FF:FF:FF:FF:FF (broadcast)
       source E0:3F:49:81:2E:EA
       type IP (0800)
IP4:   0.0.0.0 -> 255.255.255.255
       IHL 20, ver 4, tos 0, len 305, ttl 254, prot UDP, chksum BBBB (ok)
       id 0001, ofs 0
UDP:   0.0.0.0 (68) -> 255.255.255.255 (67), sock 01547160
       len 285, chksum 06B0 (ok)
277:   0000: 01 01 06 00 31 DB 51 D7-00 00 80 00 00 00 00 00 ....1█Q╫..Ç.....
       0010: 00 00 00 00 00 00 00 00-00 00 00 00 E0 3F 49 81 ............α?Iü
       0020: 2E EA 00 00 00 00 00 00-00 00 00 00 00 00 00 00 .Ω..............
       0030: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       0040: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       0050: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       0060: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       0070: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       0080: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       0090: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       00A0: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       00B0: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       00C0: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       00D0: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
       00E0: 00 00 00 00 00 00 00 00-00 00 00 00 63 82 53 63 ............céSc
       00F0: 35 01 01 3D 07 01 E0 3F-49 81 2E EA 39 02 02 24 5..=..α?Iü.Ω9..$
       0100: 37 12 01 03 06 08 09 0C-0F 17 1A 23 24 25 07 2C 7..........#$%.,
       0110: 2E 2F 42 43 FF                                  ./BC 
```

But my router never replies to it!?!
Use a `debug.file = stdout` to test if you like.

**Comment by gvanem** [comment] 2020-01-31 15:27
After further trial and error, I fail to find the cause of this bug. It will have to wait.

**Comment by Lethja** [comment] 2023-12-14 00:01
`discover_loops` is never incremented on any build and `DHCP_state` is never `DHCP_state_BOUND` on 16-bit builds. 
```diff
--- a/src/pcdhcp.c
+++ b/src/pcdhcp.c
@@ -1128,6 +1128,7 @@ int DHCP_do_boot (void)
   while (DHCP_state != DHCP_state_BOUND)
   {
     tcp_tick (NULL);
+    printf("Retry %d of %d\n", discover_loops, max_retries); /* Prints "Retry 1 of 3" forever on 16-bit builds */
     if (discover_loops >= max_retries)  /* retries exhaused */
        break;
   }
```
It seems like breakout conditions for this loop are being set elsewhere, either in `tcp_tick()` or perhaps `DAEMON_ADD (dhcp_fsm)` from a few lines above. Either way, we could prevent soft locking the machine by checking if ~10 seconds have passed since entering the loop and maybe even call `putc('.')` every second or two so the end user knows the program is still running.

Quick test code:
```c
/* Compile for DOS (Open Watcom) with 
 * `WCC -0 -bt=dos -i=INC -ml IPCONFIG` then 
 * `WLINK SYS dos LIBF LIB\WATTCPWL.LIB F IPCONFIG`
 * 
 * Compile for DOS4G (Open Watcom) with 
 * `WCC386 -3 -bt=dos -i=INC -mf IPCONFIG` then 
 * `WLINK SYS dos4g LIBF LIB\WATTCPWF.LIB F IPCONFIG`
 */

#include <stdio.h>
#include <tcp.h>

int main() {
	struct in_addr addr;

	sock_init();
	addr.s_addr = htonl(my_ip_addr);
	printf("Address: %s\n", inet_ntoa(addr));

	return 0;
}
```

Code ran on 86Box with the following virtual machine specs:
- IBM 5150 (1982)
- Intel 8088 @ 4.77Mhz
- 256k Memory
- 384k IBM PC/XT Memory Expansion
- [ISA] EGA
- [ISA] Novell NE1000

**Comment by gvanem** [comment] 2023-12-16 07:33
@mateuszviste So perhaps after so long time DHCP works better for you on 16-bit DOS?
I have no way to test this.

**Comment by Lethja** [comment] 2023-12-16 23:21
> I have no way to test this.

I'm using [DOSBox-X](https://github.com/joncampbell123/dosbox-x) to debug this problem. It can emulate a Novell NE2000 and allows you to mount directories from the host system as a drive letter

**Comment by gvanem** [comment] 2023-12-18 09:17
Applying your patch, I see the same on Windows too (with a `myip = dhcp`). 
I started `windump -nettt port 67` while running Windows version of a `tracert.exe -q2 -d www.google.com`:
```
00:00:00.000000 d8:bb:c1:06:16:48 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 319: 0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from d8:bb:c1:06:16:48, length 277
00:00:00.000927 d8:eb:97:30:89:a1 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 342: 10.0.0.1.67 > 255.255.255.255.68: BOOTP/DHCP, Reply, length 300
```

The tracert / Watt-32 output is simply:
```
`c:\temp\w32dhcp.tmp' not found
Configuring through DHCP..DHCP open: brdcast(1) srvr(0.0.0.0)
After Yield
INIT/SEND_TIMEOUT: Sending DHCP discover (1)
.....failed
Configuring through RARP...failed
```

So my router (`10.0.0.1`) does reply to the initial DHCP Discover and gives me an IP-address. 
It even says so in it's syslog message:
```
10.0.0.1, Dec 18 10:12:09 dnsmasq-dhcp[3070]: DHCPDISCOVER(br-lan) d8:bb:c1:06:16:48
10.0.0.1, Dec 18 10:12:09 dnsmasq-dhcp[3070]: DHCPOFFER(br-lan) 10.0.0.98 d8:bb:c1:06:16:48
```

But the Watt-32 version is deaf for some reason. Hm...

**Comment by Lethja** [comment] 2023-12-18 09:55
> Applying your patch, I see the same on Windows too

What makes this more awkward is that the DOS4GW version works correctly
```
C:\>IPCON4GW.EXE
DOS/4GW Protected Mode Run-time  Version 1.97
Copyright (c) Rational Systems, Inc. 1990-1994
Configuring through DHCP..After Yield
...After Yield
sock_dataready
sock_fastread
.After Yield
After Yield
sock_dataready
sock_fastread
.Address: 192.168.1.29
```

**Comment by gvanem** [comment] 2023-12-18 10:21
From the same sources? Which program did you test that with?

**Comment by Lethja** [comment] 2023-12-18 11:16
> From the same sources? Which program did you test that with?

Yes the exact same sources. After running `configur.bat` and adjusting `config.h` I run `wmake -h -f watcom_l.mak` and `wmake -h -f watcom_f.mak` from a DOS environment with Open Watcom 1.9. I've been testing with a very basic `ipconfig` program I posted [in this comment](https://github.com/gvanem/Watt-32/issues/4#issuecomment-1854876941) against these builds

**Comment by Lethja** [comment] 2023-12-18 23:33
After some more tinkering it looks like the daemon simply never fires again. There's also a ton more in the rundown dump of the i386 build. Things like tftp and dynip that I didn't explicitly turn on for this build. It's possible that hardcoded conditional statement are enabling code that DHCP depends on. Take a look at this snippet from the middle of `config.h` for example:

```c
/*
 * Add some more options for djgpp, HighC, 32-bit Watcom/DMC and Win32/64
 */
#if defined(__DJGPP__) || defined(__HIGHC__) || defined(WATCOM386) || \
    defined(DMC386) || defined(_WIN32) || defined(_WIN64)
  #define USE_ECHO_DISC
  #define USE_RARP
  #define USE_IPV6
  #define USE_IDNA
  #define USE_TCP_MD5
  #define USE_GZIP
  #define USE_DYNIP_CLI
//#define USE_SCTP
  #define USE_DEAD_GWD
#endif
```

Updated test code:
```c
/* Compile for DOS (Open Watcom) with 
 * `WCC -0 -bt=dos -i=INC -ml IPCONFIG` then 
 * `WLINK SYS dos LIBF LIB\WATTCPWL.LIB F IPCONFIG`
 * 
 * Compile for DOS4G (Open Watcom) with 
 * `WCC386 -3 -bt=dos -i=INC -mf IPCONFIG` then 
 * `WLINK SYS dos4g LIBF LIB\WATTCPWF.LIB F IPCONFIG`
 */

#include <stdio.h>
#include <tcp.h>

int main() {
	struct in_addr addr;

	tcp_set_debug_state(3);
	dbug_init();

	sock_init();
	addr.s_addr = htonl(my_ip_addr);
	printf("Address: %s\n", inet_ntoa(addr));

	return 0;
}
```
DOS 16-bit output:
```
Parsing `.\wattcp.cfg' (pass 1)
Parsing `.\wattcp.cfg' (pass 2)
ARG_FUNC   , matched `MY_IP' = `dhcp'
rundown_dump():
  order   3: `restore_sig_handlers'  called from sock_ini.c (892)
  order   5: `dbug_exit'  called from pcdbug.c (306)
  order  10: `__eth_release'  called from pcsed.c (704)
  order 259: `DHCP_exit'  called from pcdhcp.c (1435)
  order 303: `exit_localport'  called from ports.c (59)
  order 1000: `daemon_clear_cdecl'  called from sock_ini.c (841)
  okay
Configuring through DHCP..Running daemon 0 (arp_daemon)
Running daemon 1 (dhcp_fsm)
................................failed
Calling rundown-func `restore_sig_handlers' at order 3
Calling rundown-func `dbug_exit' at order 5
Calling rundown-func `__eth_release' at order 10
Calling rundown-func `DHCP_exit' at order 259
Calling rundown-func `exit_localport' at order 303
Calling rundown-func `daemon_clear_cdecl' at order 1000
```
DOSW4G output:
```
DOS/4GW Protected Mode Run-time  Version 1.97
Copyright (c) Rational Systems, Inc. 1990-1994
Parsing `.\wattcp.cfg' (pass 1)
idna.c(164): iconv_init: codepage 858
Parsing `.\wattcp.cfg' (pass 2)
ARG_FUNC   , matched `MY_IP' = `dhcp'
rundown_dump():
  order   3: `restore_sig_handlers'  called from sock_ini.c (892)
  order   5: `dbug_exit'  called from pcdbug.c (306)
  order  10: `__eth_release'  called from pcsed.c (704)
  order  15: `free_selector'  called from misc.c (1249)
  order 200: `res_exit'  called from res_init.c (298)
  order 258: `echo_discard_exit'  called from echo.c (123)
  order 259: `DHCP_exit'  called from pcdhcp.c (1435)
  order 261: `tftp_exit'  called from tftp.c (581)
  order 262: `dynip_exit'  called from dynip.c (128)
  order 301: `printk_exit'  called from printk.c (170)
  order 303: `exit_localport'  called from ports.c (59)
  order 1000: `daemon_clear_cdecl'  called from sock_ini.c (841)
  okay
Configuring through DHCP..Running daemon 0 (arp_daemon)
Running daemon 1 (dhcp_fsm)
.Running daemon 0 (arp_daemon)
Running daemon 1 (dhcp_fsm)
..Running daemon 0 (arp_daemon)
Running daemon 1 (dhcp_fsm)
...Running daemon 0 (arp_daemon)
Running daemon 1 (dhcp_fsm)
value 3232235779 duplicated in array 002954b8
Address: 192.168.1.29
Calling rundown-func `restore_sig_handlers' at order 3
Calling rundown-func `dbug_exit' at order 5
Calling rundown-func `__eth_release' at order 10
Calling rundown-func `free_selector' at order 15
Calling rundown-func `res_exit' at order 200
Calling rundown-func `echo_discard_exit' at order 258
Calling rundown-func `DHCP_exit' at order 259
Calling rundown-func `free_frag_buckets' at order 260
Calling rundown-func `tftp_exit' at order 261
Calling rundown-func `dynip_exit' at order 262
Calling rundown-func `printk_exit' at order 301
Calling rundown-func `exit_localport' at order 303
Calling rundown-func `daemon_clear_cdecl' at order 1000
```

**Comment by gvanem** [comment] 2023-12-19 07:03
Strange that `DOSW4G output:` works since it should be with `WATCOM386`. No?
And `WIN32` + `WIN64` does *not* work with `my_ip = dhcp`; it should have the same `config.h` settings as `WATCOM386`.
So probably some issue with timers again. 

But I admit that this `daemon_run()` stuff is an ugly hack. 
It should perhaps not be used for `dhsp_fsm()` since it's already blocking.

**Comment by Lethja** [comment] 2023-12-19 08:15
> Strange that `DOSW4G output:` works since it should be with `WATCOM386`. No?

I have put some junk into that precompiler conditional to prevent it from compiling to confirm that indeed it is enabled with `wmake -h -f watcom_f.mak` (and disabled with `wmake -h -f watcom_l.mak`)

> But I admit that this `daemon_run()` stuff is an ugly hack. It should perhaps not be used for `dhsp_fsm()` since it's already blocking.

I agree `pcbootp.c` is very straight forward and works on 16-bit perfectly (I'm assuming it works on Windows as well). The problem `dhcp_fsm` is trying to solve is that the DHCP address lease could expire and should be renewed in the middle of a programs operation.

**Comment by Lethja** [comment] 2023-12-19 08:57
> If I link my application against the older WATT-32 2.2 rel 10, then DHCP works fine.

I just tried this. 16-bit builds (`wmake -h -f watcom_l.mak`) from dd9e063 work perfectly and still contain the daemon code. 

DOS 16-bit output:
```
Parsing `.\wattcp.cfg' (pass 1)
Parsing `.\wattcp.cfg' (pass 2)
ARG_FUNC   , matched `MY_IP' = `dhcp'
rundown_dump():
  order   3: restore_sig_handlers
  order   5: dbug_exit
  order  10: _eth_release
  order 259: DHCP_exit
  order 303: exit_localport
  okay
Configuring through DHCP..Running daemon 0 (09a1:4898)
Running daemon 1 (09a1:d5e0)
Running daemon 0 (09a1:4898)
Running daemon 1 (09a1:d5e0)
Running daemon 0 (09a1:4898)
Running daemon 1 (09a1:d5e0)
Running daemon 0 (09a1:4898)
Running daemon 1 (09a1:d5e0)
Address: 192.168.1.29
Calling rundown-func `restore_sig_handlers' at order 3
Calling rundown-func `dbug_exit' at order 5
Calling rundown-func `_eth_release' at order 10
Calling rundown-func `DHCP_exit' at order 259
Calling rundown-func `exit_localport' at order 303
```
Notable by it's absence are some changes made in 2007...
```diff
--- a/src/pcdhcp.c
+++ b/src/pcdhcp.c
@@ -5,7 +5,7 @@
  *  if no WATTCP.CFG file is found.
  */
 
-/*  Copyright (c) 1997-2002 Gisle Vanem <giva@bgnett.no>
+/*  Copyright (c) 1997-2007 Gisle Vanem <gvanem@yahoo.no>
  *
  *  Redistribution and use in source and binary forms, with or without
  *  modification, are permitted provided that the following conditions
@@ -60,6 +60,11 @@
  *
  *  \version 0.93: Jul 2, 2004:
  *    Fixed logic around reading transient config.
+ *
+ *  \version 0.94: Oct 22, 2007:
+ *    Fixes for Linux dhcp servers: parse dhcp options in ACK msgs.
+ *    Changed DHCP_do_boot() to handle renew and rebind as well as init.
+ *    Renegotiate lease if past the renew or rebind times.
  */
```

**Comment by gvanem** [comment] 2023-12-19 11:09
The commands:
```
git diff 2439d68117cae59714b2e874393506defed05116 > t.1
git diff a267c58debd6ff48cc8fdb0ef042c99e112bc428 > t.2
```
gives 13+11 MByte files! This will be tricky to figure out.

**Comment by Lethja** [comment] 2023-12-20 01:45
#98 seems to fix the issue

**Comment by gvanem** [comment] 2023-12-20 08:09
I did not mean to close this (but the PR that should fix it). I'll reopen this issue to verify that it indeed was fixed for the OP.

**Comment by mateuszviste** [comment] 2023-12-20 08:20
Thanks for reopening it, Gisle. And many thanks to Lethja and Jwc for their impressive involvement. This all looks very promising.
I had hit the issue in 2020 during development of Gopherus <https://gopherus.sourceforge.net/> ; as a workaround I simply kept using an older release of Watt32 since then.
I will make the effort to setup a proper build environment (hopefully before the end of the year) and test this fixed version of Watt32 to confirm it indeed solves the initial issue.

**Comment by gvanem** [comment] 2023-12-20 13:28
> I had hit the issue in 2020 during development of Gopherus https://gopherus.sourceforge.net/ ;

I tried to build this just now with Watt-32. But failed on the ncurses stuff. I see the SDL UI is gone :-(
How about a UI for S-Lang?

**Comment by Lethja** [comment] 2023-12-24 14:25
I've built [gopherus-1.2.2.tar.xz](https://gopherus.sourceforge.net/gopherus-1.2.2.tar.xz) with a400bd140bc377a70b6e1146919e7ef156f1f893 for 16-bit DOS. Everything appears to be working well ([gopherus.zip](https://github.com/gvanem/Watt-32/files/13762089/gopherus.zip))

**Comment by gvanem** [comment] 2024-01-24 07:02
The issue seems to be resolved. Hence closing.

**Closed by gvanem** 2024-01-24 07:02 UTC
Labels: bug, help wanted
